#+title: Whoops
#+date: <2015-10-19 Mon>

Whoops, a little late today, to be fair to myself, I was a little
distracted. First, wasted a few hours sorting out our VMWare servers
at work. Then, I decided I would call up the department of transport
to find out why I hadn't got my refund for my car rego. You see, I had
handed in my licence plates over a month ago, and thought I would
chase them up. Well, it seems they lost them and have no record to
receiving them.

This means that I had to fill out that they were lost, and I can't get
the credit backdated from the date of my accident.

So, not only am I out of pocket for the refund that I miss, I've also
missed out on the hours that I had to spend to sort the problem out.
To add insult to injury, this is all their fault, I have to pay for
their mistake. Being a government department, I can't take my business
elsewhere, there's no recourse. They don't pay for their mistakes, one
has to wonder how much has been wasted of other people's money.

If you run a business, don't make your customers pay for your
mistakes.
