#+title: Drinking the Emacs firehose.
#+date: <2015-02-19 Thu>
#+filetags:

In my wanderings of the Internet, I can't really remember what I was searching for, something Emacs related, I came across an interesting blog. [[http://sachachua.com/blog/][Living an awesome life]], is the blog of [[http://sachachua.com/blog/about][Sacha Chua]] a software developer who is very heavily into both blogging (her blog has regular posts spanning back to 2001), and organising her life using Emacs. Wow, really, wow. Her productivity really puts me to shame, so, I've been inspired.

I've decided that my current hobbyist usage of Emacs, and general organisation skills are simply not up to par and I should really make the effort to get better organised. Part of that is to actually blog regularly, and switch to using Emacs for everything I can.

The first stage being to switch to using Gnus to read my e-mails. Which I've done. It's still a little rough, but I can read and reply to e-mails (and it seems to be working). This also has a bonus, I can link to my e-mails from [[http://orgmode.org/][org-mode]]! Next thing I want to do is get my org-mode workflow a bit smoother, and then try to get any blogging as friction-less as possible.
