#+title: Small Business
#+date: <2015-10-16 Fri>

I work in a small business, been here for about twelve years now.
Started off as just an unqualified technical helper/IT guy, then moved
onto being the bookkeeper for a few years, and now I'm the general
manager. It's an interesting thing, a small business, you just have to
make do with what you can.

That's probably not a good description, because at an enterprise level
company you have to make do with what you can, it's just on a larger
scale. But, for example, I have a problem with some servers, now,
because of me, we have a server setup a little bit more...
comprehensive, then most companies.

Anyway, problems with servers, they're just Sun Fire X4600 M2s, 64GB
RAM, got them off eBay. They're old, but they work. Well, obviously
not working fully now otherwise I wouldn't be talking about this. So,
right, I thought I would price up some Dell servers, I made the switch
from custom building PCs to using Dell desktops, so thought I would
try the same with servers.

Looking at a basic sort of rack computer config, with 64GB RAM, over a
few thousand dollars. We can't justify that. Just a quick look, on
eBay, and I can find a Sun Fire X4450 with 64GB RAM, 16 cores, for
$1000 or so. Now this isn't a nice new setup with support, and is far
more powerful. However, I could buy eight of these things for the same
price.

Small businesses, obviously have different considerations when making
purchases. But, small businesses can grow and now I will sort of try
to get to the point I just thought up. Well, I've had it on my mind
for a little bit.

Why the hell is it hard to get good accounting software that can grow
with a company from the start? We used MYOB for a few years, but we
outgrew it. Sure, MYOB has an API, but, really, it's shit, you can't
use it to extend the software. Recent versions of MYOB have now moved
to the "cloud", you know that software as a service thing (which is
not necessarily bad), and now give you a REST API, but it still makes
things difficult to extend in a way that you can use to customise to
match your company workflow.

We moved to Greentree, that was a mistake, one which I will do into
later.
