#+title: Habits And Practice
#+date: 2015-10-15

I've read a few time management books over the years, the three ones that I can remember right now: [[http://www.amazon.com/o/asin/0143126563?tag%3Dluminou-20][Getting Things Done]], [[http://www.amazon.com/o/asin/B00VGAATMC?tag%3Dluminou-20][The Pomodoro Technique]], and [[http://www.amazon.com/o/asin/0340909129?tag%3Dluminou-20][Do It Tomorrow]]. Each have their own take on how to manage your time, and they can all be combined in whatever way you like that works for you. But I have a problem, I'm just not productive.

I think, mostly, is a lack of motivation, and I'm not sure how to go about sorting this out. I think I have fallen into the habit of being unproductive and it's something I have to work to get out of. I'm not sure.

This is something that is personal, so I don't think that there's much that anybody else can do about it? So, I'm going to try an experiment, I'm going to see if I can get into the habit of posting on this blog everyday, at least once. The posts don't have to be anything interesting, they don't have to have some deeper meaning, this blog is just for me after all.

But, I will have to post before, say, lunchtime, of everyday. Has to be at least one sentence. Lets see what happens if I follow this for a month.
