#+title: Twitch Streaming
#+date: 2018-10-05
#+description: I'm starting out on Twitch, and I'm going to blog about it.
#+tags: Twitch Streaming Beginner

So, I've started streaming on Twitch, and thought I probably should
write about it. There are many YouTube videos and Twitch streamers who
have useful tips and information for new streamers. However, I'm not
familiar with anyone who is doing something similar, but, honestly I
haven't looked too hard.

This won't be a blog, or discussion about how to do streaming on a
budget, although I can't afford to go crazy with money, I do have a
day job, and an income that I can spend some on my streaming setup. I
generally have to sell some things I have on Ebay to try and make up
the funds for purchases.

So, what are my motivations for streaming? Good question! Honestly, I
really want to be able to play games (typically with friends) for a
substantial amount of time. At the moment, on weekdays, I come home
from work, try to help with the kids, eat tea, get the kids ready for
bed, then watch TV with my wife until she goes to bed.

Around this time (9:30PM to 10:00PM) is the time where I get to play
some games. Since I have to work the next day, midnight is generally
the latest I should be staying up. Doing this schedule for five hours
a week is a bit punishing, since I have to work the next day, and I'm
not at my best. So, I have just recently, cut down to only doing it
Monday, Wednesday, and Friday.

Now, if I could get a good enough income from streaming, then I would
have the flexibility with my hours, spend time with the kids after
they come home from school, and get a better sleep cycle.

I honestly don't expect to be a top tier streamer, making $250,000 a
month streaming. But, I would like to be in a position where I can
make it a full-time job, so I can justify spending more money and time
on gaming. I'm already in a decent enough financial position that I
don't need an income from Twitch, et al, so it's pretty low risk in
that regard.

Anyway, I figure I might as well blog about it, since I haven't
blogged on here for awhile. I really need some subject matter to blog
about, and lacking a subject that I'm a real expert on, I figured I
would just blog about something that I'm hoping to learn.
